name: 혼자어때 CI

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-verson: 18
          cache: yarn

      - name: Install node package
        run: yarn

      - name: Check build
        run: yarn build
